version: '2'

services:
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.2.4
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  # Define a Chronograf service
  chronograf:
    image: chronograf:1.3
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb

  # Define a Chronograf service
  grafana:
    image: grafana/grafana:4.4.3
    ports: 
      - "3000:3000"
    links:
      - influxdb
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
            
  # Define a service for using the influx CLI tool.
  spring-influx:
    build:
      context: .
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports: 
      - "8080:8080"
    depends_on:
      - influxdb
    links:
      - influxdb